build:
  version: "3.0.0"

accounts:
  # noinspection SpringBootApplicationYaml
  message: "Welcome to Accounts Rest API Service"
  contactDetails:
    name: "Anuj Sharma"
    email: "xYRf4@example.com"
  onCallSupport:
    -(876)9060653
