build:
  version: "1.0.0"

accounts:
  # noinspection SpringBootApplicationYaml
  message: "Welcome to Accounts Prod Rest API Service"
  contactDetails:
    name: "{cipher}90dc1d177f9a7e29888040a1f1c270657c3066f935e23180f48cc0148819e34a"
    email: "xYRf4@example.com"
  onCallSupport:
    -(666)9060653