build:
  version: "1.0.0"

cards:
  # noinspection SpringBootApplicationYaml
  message: "Welcome to Cards Production Rest API Service"
  contactDetails:
    name: "Riphel Sharma"
    email: "riphel@gmail.com"
  onCallSupport:
    -(666)9060653