build:
  version: "1.0.0"

loans:
  # noinspection SpringBootApplicationYaml
  message: "Welcome to Loans Production Rest API Service"
  contactDetails:
    name: "John Doe"
    email: "doe@gmail.com"
  onCallSupport:
    -(666)9060653